version: '3.3'

services:
    flask_e7:
        build: .
        ports:
            - 5000:5000
        depends_on:
            - redis
            - mongodb
    
    redis:
        container_name: redis_e7
        image: redis
    
    mongodb:
        container_name: mongo_e7
        image: mongo

        