version: '3.3'

services:
    flask_e7:
        build: .
        ports:
            - 5000:5000
        depends_on:
            - redis
    
    redis:
        container_name: redis_e7
        image: redis
        ports:
            - 6379:6379


        